name: Daily Repository Update

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Simple test step
        run: echo "Hello World" 
